name: tokenized-strategy-ape-mix

plugins:
  - name: solidity
  - name: etherscan
  - name: infura
  - name: alchemy
  - name: foundry

default_ecosystem: ethereum

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.2
  - name: tokenized-strategy
    github: yearn/tokenized-strategy
    ref: v3.0.1
    contracts_folder: src
    exclude:
      - test/
  - name: periphery
    github: yearn/tokenized-strategy-periphery
    ref: master
    contracts_folder: src
    exclude:
      - test/

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.2"
    - "@tokenized-strategy=tokenized-strategy/v3.0.1"
    - "@periphery=periphery/master"

ethereum:
  default_network: mainnet-fork
  local:
    default_provider: foundry
  
foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: http://192.168.1.102:8545
